apiVersion: v1
kind: Pod
metadata:
  name: app2
  labels:
    app: webapp2
spec:
  containers:
  - image: takytaky/app:v1
    name: app-container2
    ports:
    - containerPort: 80
      protocol: TCP

  - name: sidecar-container
    image: rusita/sidecar:curl
    command: ["tail"]
    args: ["-f", "/dev/null"]