apiVersion: v1
kind: Pod 
metadata:
  name: annotation-nodejs
  labels:
    app: nodejs
  annotations:
    manufacturer: "takytaky"
    e-mail: "takytaky@example.com"
    release-version: "v1"
spec:
  containers:
  - name: nodejs
    image: takytaky/app:v1
    ports:
    - containerPort: 80
