apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: metallb-ip 
      protocol: layer2
      addresses:
      - 192.168.137.200-192.168.137.209
