apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
  - name: volume-pod
    image: takytaky/app:log
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/tmp"
      name: app-vol
  volumes:
  - name: app-vol
    persistentVolumeClaim:
      claimName: pvc
