FROM centos

ENV myName “Yu Mi”
ENV myOrder Pizza Pasta Salad
ENV myNumber 1004

LABEL maintainer "Yu Mi <yumi@example.com>"
LABEL title "TEST Image"
LABEL version 1.0
LABEL description "This image is test image ^__^"

